name: DecoHeads
main: com.rayzr522.decoheads.DecoHeads
version: 1.0
description: Adds lots of decorative heads that can be used for building / design
author: Rayzr522
commands:
  decoheads:
    description: Opens the DecoHeads inventory
    aliases:
    - dh
    - heads
    usage: /decoheads [reload|rl]