name: DecoHeads
main: me.rayzr522.decoheads.DecoHeads
version: ${project.version}
description: Adds lots of decorative heads that can be used for building / design
author: Rayzr522
url: ${project.url}
commands:
  decoheads:
    description: Opens the DecoHeads inventory
    aliases: [dh, heads]
    usage: Oops! Something went wrong!
