name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Prepare artifact
      run: |
        mkdir -p output
        mv target/DecoHeads-*.jar output
    - uses: actions/upload-artifact@master
      with:
        name: DecoHeads JAR
        path: output
